SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '788howrxwmr87f'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'Rb8GJciOM66YSixo'
SOCIAL_AUTH_TWITTER_KEY = 'I7OFlNPIiVY2yyMfRtmQxtCn8'
SOCIAL_AUTH_TWITTER_SECRET = 'fQxfUNYWamWh7UuQul6YQxitDOvMPiN50MyLhBFLbQYk7j4EKo'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'

